# Generated by Django 3.0.5 on 2020-04-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actions_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='cars',
            new_name='car_id',
        ),
    ]
