# Generated by Django 3.0.5 on 2020-04-28 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_actions_user_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actions',
            name='last_update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_last_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actions',
            name='user_client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_client_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cars',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cars',
            name='last_update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_last_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instruments',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instruments',
            name='last_update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_last_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='last_update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_last_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spares',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spares',
            name='last_update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spares_last_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='user_staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_staff_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
